# Generated by Django 4.2.7 on 2026-02-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securityevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityevent',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='password_re_token_h_18eb98_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='password_re_expires_8e96b7_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='requested_ip',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='requested_user_agent',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='used_ip',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='used_user_agent',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
    ]
