# Generated by Django 4.2.7 on 2026-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_log_entry_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsetting',
            name='log_entry_tolerance_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Default tolerance window in minutes (±) for log entry time. 0 = no tolerance.'),
        ),
    ]
