# Generated by Django 4.2.7 on 2026-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sessionsetting_log_entry_tolerance_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsetting',
            name='log_entry_tolerance_minutes',
        ),
    ]
