# Generated by Django 4.2.7 on 2026-01-06 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('utility', 'E Log Book'), ('chemical', 'Chemical Prep'), ('validation', 'HVAC Validation'), ('air_velocity', 'Air Velocity Test'), ('filter_integrity', 'Filter Integrity Test'), ('recovery', 'Recovery Test'), ('differential_pressure', 'Differential Pressure Test'), ('nvpc', 'NVPC Test')], max_length=50)),
                ('source_id', models.UUIDField(help_text='ID of the original log/test entry')),
                ('source_table', models.CharField(help_text='Name of the source table', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['report_type', 'approved_at'], name='reports_report__273eb1_idx'), models.Index(fields=['source_id', 'source_table'], name='reports_source__603e5c_idx')],
            },
        ),
    ]
