# Generated by Django 4.2.7 on 2026-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('limit_update', 'Limit Update'), ('config_update', 'Configuration Update'), ('log_update', 'Log Update'), ('log_correction', 'Log Correction'), ('user_created', 'User Created'), ('password_changed', 'Password Changed'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked')], max_length=64),
        ),
    ]
