# Generated by Django 4.2.7 on 2026-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('limit_update', 'Limit Update'), ('config_update', 'Configuration Update'), ('log_update', 'Log Update'), ('log_correction', 'Log Correction'), ('log_created', 'Log Created'), ('log_approved', 'Log Approved'), ('log_rejected', 'Log Rejected'), ('log_deleted', 'Log Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('password_changed', 'Password Changed'), ('user_locked', 'User Locked'), ('user_unlocked', 'User Unlocked'), ('login', 'Login'), ('logout', 'Logout'), ('equipment_update', 'Equipment Update')], max_length=64),
        ),
    ]
