# Generated by Django 4.2.7 on 2026-01-05 05:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('chiller', 'Chiller'), ('boiler', 'Boiler'), ('compressor', 'Compressor')], max_length=20)),
                ('equipment_id', models.CharField(db_index=True, max_length=100)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('t1', models.FloatField(help_text='Temperature 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('t2', models.FloatField(help_text='Temperature 2', validators=[django.core.validators.MinValueValidator(0)])),
                ('p1', models.FloatField(help_text='Pressure 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('p2', models.FloatField(help_text='Pressure 2', validators=[django.core.validators.MinValueValidator(0)])),
                ('flow_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_utility_logs', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utility Log',
                'verbose_name_plural': 'Utility Logs',
                'db_table': 'utility_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='UtilityReading',
        ),
    ]
