# Generated by Django 4.2.7 on 2026-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_approved_at_equipment_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
    ]
