# Generated by Django 4.2.7 on 2026-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_log_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tolerance_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Per-equipment tolerance window in minutes (±). 0 = no tolerance.'),
        ),
    ]
