# Generated by Django 4.2.7 on 2026-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_tolerance_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='tolerance_minutes',
        ),
    ]
