# Generated by Django 4.2.7 on 2026-01-05 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(db_index=True, max_length=100)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chiller_supply_temp', models.FloatField(help_text='Chiller supply temperature (°C)', validators=[django.core.validators.MinValueValidator(0)])),
                ('chiller_return_temp', models.FloatField(help_text='Chiller return temperature (°C)', validators=[django.core.validators.MinValueValidator(0)])),
                ('cooling_tower_supply_temp', models.FloatField(help_text='Cooling tower supply temperature (°C)', validators=[django.core.validators.MinValueValidator(0)])),
                ('cooling_tower_return_temp', models.FloatField(help_text='Cooling tower return temperature (°C)', validators=[django.core.validators.MinValueValidator(0)])),
                ('ct_differential_temp', models.FloatField(help_text='CT differential temperature (°C)', validators=[django.core.validators.MinValueValidator(0)])),
                ('chiller_water_inlet_pressure', models.FloatField(help_text='Chiller water inlet pressure (bar)', validators=[django.core.validators.MinValueValidator(0)])),
                ('chiller_makeup_water_flow', models.FloatField(blank=True, help_text='Chiller makeup water flow (LPH)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chiller_logs', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiller_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chiller Log',
                'verbose_name_plural': 'Chiller Logs',
                'db_table': 'chiller_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
