# Generated by Django 4.2.7 on 2026-02-27 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chiller_logs', '0003_chillerlog_footer_chemicals_and_blowdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChillerEquipmentStatusAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('cooling_tower_pump_status', 'Cooling Tower Pump 1/2'), ('chilled_water_pump_status', 'Chilled Water Pump 1/2'), ('cooling_tower_fan_status', 'Cooling Tower Fan 1/2/3')], max_length=64)),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiller_equipment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('chiller_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_status_audits', to='chiller_logs.chillerlog')),
            ],
            options={
                'verbose_name': 'Chiller Equipment Status Audit',
                'verbose_name_plural': 'Chiller Equipment Status Audits',
                'db_table': 'chiller_equipment_status_audits',
                'ordering': ['-changed_at'],
            },
        ),
    ]
