# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chiller_logs', '0007_drop_approval_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chillerlog',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('pending_secondary_approval', 'Pending secondary approval'),
                ],
                default='draft',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='secondary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chillerlog',
            name='secondary_approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='secondary_approved_chiller_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
