# Generated by Django 4.2.7

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chiller_logs", "0016_delete_coolingtowerchemicallog"),
    ]

    operations = [
        migrations.AddField(
            model_name="chillerequipmentlimit",
            name="electricity_rate_rs_per_kwh",
            field=models.FloatField(
                blank=True,
                help_text="Electricity rate (Rs/kWh) for cost calculation",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
