# Generated by Django 4.2.7 on 2026-03-12 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiller_logs', '0017_chillerequipmentlimit_electricity_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chillerequipmentstatusaudit',
            name='field_name',
            field=models.CharField(choices=[('cooling_tower_pump_status', 'Cooling Tower-1 1/2'), ('chilled_water_pump_status', 'Chilled Water Pump 1/2'), ('cooling_tower_fan_status', 'Cooling Tower Fan 1/2/3')], max_length=64),
        ),
        migrations.AlterField(
            model_name='chillerlog',
            name='cooling_tower_chemical_name',
            field=models.CharField(blank=True, help_text='Cooling tower-1 chemical name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chillerlog',
            name='cooling_tower_chemical_qty_per_day',
            field=models.FloatField(blank=True, help_text='Cooling tower-1 chemical quantity added per day (kg)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chillerlog',
            name='cooling_tower_pump_status',
            field=models.CharField(blank=True, help_text='Cooling tower-1 1/2 status (On/Off)', max_length=50, null=True),
        ),
    ]
