# Generated by Django 4.2.7 on 2025-12-31 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(default='svu-enterprises', max_length=100)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('safety', 'Safety'), ('validation', 'Validation'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('fields', models.JSONField(default=list)),
                ('workflow', models.JSONField(blank=True, default=dict)),
                ('display', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logbook Schema',
                'verbose_name_plural': 'Logbook Schemas',
                'db_table': 'logbook_schemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(default=dict)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_logbook_entries', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logbooks.logbookschema')),
            ],
            options={
                'verbose_name': 'Logbook Entry',
                'verbose_name_plural': 'Logbook Entries',
                'db_table': 'logbook_entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
