# Generated by Django 4.2.7 on 2026-01-02 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookschema',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LogbookRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('super_admin', 'Super Admin'), ('client', 'Client')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_logbook_roles', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='logbooks.logbookschema')),
            ],
            options={
                'verbose_name': 'Logbook Role Assignment',
                'verbose_name_plural': 'Logbook Role Assignments',
                'db_table': 'logbook_role_assignments',
                'ordering': ['role'],
                'unique_together': {('schema', 'role')},
            },
        ),
    ]
