# Generated by Django 4.2.7 on 2025-12-31 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('calibration_date', models.DateField()),
                ('calibration_due_date', models.DateField()),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring', 'Expiring'), ('expired', 'Expired')], default='valid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'db_table': 'instruments',
                'ordering': ['calibration_due_date'],
            },
        ),
    ]
