# Generated by Django 4.2.7 on 2026-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['-calibration_due_date'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='status',
        ),
        migrations.AddField(
            model_name='instrument',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instrument',
            name='site_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
