# Generated by Django 4.2.7 on 2026-01-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_options_remove_instrument_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='metadata',
        ),
    ]
