# Generated by Django 4.2.7 on 2025-12-31 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('iso_class', models.IntegerField(choices=[(5, 'ISO 5'), (6, 'ISO 6'), (7, 'ISO 7'), (8, 'ISO 8')])),
                ('room_volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('grid_readings', models.JSONField(default=list)),
                ('average_velocity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flow_rate_cfm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cfm', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ach', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('design_spec', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='air_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Air Validation',
                'verbose_name_plural': 'Air Validations',
                'db_table': 'air_validations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
