# Generated by Django 4.2.7 on 2026-01-05 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_validation', '0002_rename_to_hvac_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvacvalidation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hvacvalidation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hvac_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hvacvalidation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
