# Generated by Django 4.2.7 on 2026-01-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='client_id',
            field=models.CharField(db_index=True, default='svu-enterprises', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
