# Generated by Django 4.2.7 on 2026-01-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_site_customer_id_site_address_site_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='metadata',
        ),
    ]
