# Generated by Django 4.2.7 on 2025-12-31 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chemical_name', models.CharField(max_length=255)),
                ('equipment_id', models.CharField(max_length=100)),
                ('concentration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('water_volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chemical_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chemical Preparation',
                'verbose_name_plural': 'Chemical Preparations',
                'db_table': 'chemical_preparations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
