# Generated by Django 4.2.7 on 2026-01-05 05:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemical_prep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='chemical_quantity',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='water_volume',
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chemical_preparations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='checked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='chemical_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='chemical_qty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='feed_water_temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='log_type',
            field=models.CharField(choices=[('chemical', 'Chemical Preparation'), ('boiler', 'Boiler Monitoring')], default='chemical', max_length=20),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='oil_temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='solution_concentration',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='steam_flow_lph',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='steam_pressure',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='steam_temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='chemicalpreparation',
            name='water_qty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chemicalpreparation',
            name='chemical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
