# Generated by Django 4.2.7 on 2026-01-05 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0002_remove_chemicalpreparation_chemical_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='feed_water_temp',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='oil_temp',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='steam_flow_lph',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='steam_pressure',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='steam_temp',
        ),
        migrations.AlterField(
            model_name='chemicalpreparation',
            name='chemical_qty',
            field=models.FloatField(blank=True, help_text='Chemical quantity (G)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chemicalpreparation',
            name='water_qty',
            field=models.FloatField(blank=True, help_text='Water quantity (L)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
