# Generated by Django 4.2.7 on 2026-03-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0009_add_pending_secondary_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpreparation',
            name='corrects',
            field=models.ForeignKey(blank=True, help_text='If this is a correction, points to the original preparation entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='chemical_prep.chemicalpreparation'),
        ),
    ]
