# Generated by Django 4.2.7 on 2026-03-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0010_chemicalpreparation_corrects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='quantity_taken',
        ),
        migrations.RemoveField(
            model_name='chemicalpreparation',
            name='reason',
        ),
    ]
