# Generated by Django 4.2.7 on 2026-03-04 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_prep', '0011_remove_chemicalpreparation_quantity_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpreparation',
            name='chemical_concentration',
            field=models.FloatField(blank=True, help_text='Chemical concentration (%)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
